version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: zanjabil-db
    env_file: .env
    ports:
      - 5430:5432


volumes:
  postgres_data:
