# Generated by Django 4.0.5 on 2022-07-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanjabil_backend', '0008_alter_menucategory_icon_alter_menucategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
