# Generated by Django 4.0.5 on 2022-07-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zanjabil_backend', '0009_alter_menucategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zanjabil_backend.menucategory'),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
