# Generated by Django 4.0.5 on 2022-08-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanjabil_backend', '0012_alter_address_apartment_alter_address_build_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='AddressModel',
        ),
        migrations.RenameModel(
            old_name='Dish',
            new_name='DishModel',
        ),
        migrations.RenameModel(
            old_name='MenuCategory',
            new_name='MenuCategoryModel',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuModel',
        ),
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='RestaurantModel',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='dishmodel',
            options={'verbose_name_plural': 'Dish'},
        ),
        migrations.AlterModelOptions(
            name='restaurantmodel',
            options={'verbose_name_plural': 'Restaurant'},
        ),
    ]
