# Generated by Django 4.0.5 on 2022-07-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('street', models.CharField(default='', max_length=255)),
                ('longitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('isDefault', models.BooleanField(default=False)),
                ('intercom', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('build', models.CharField(default='', max_length=255)),
                ('apartment', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('preview', models.CharField(default=None, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('description', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zanjabil_backend.address')),
                ('menu_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zanjabil_backend.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('icon', models.CharField(default='', max_length=255)),
                ('dishes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zanjabil_backend.dish')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zanjabil_backend.menucategory'),
        ),
    ]
