# Generated by Django 4.0.5 on 2022-07-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanjabil_backend', '0005_rename_menu_category_restaurant_menu_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
    ]
