# Generated by Django 4.0.5 on 2022-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanjabil_backend', '0006_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu categories'},
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='dishes',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='dishes',
            field=models.ManyToManyField(to='zanjabil_backend.dish'),
        ),
    ]
